---
settings:
  name: Astra Data Store
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: ko-kr,us-en,ja-jp,zh-cn,zh-tw
sidebar:
  entries:
  - title: Astra Data Store 문서
    url: "/index.html"
  - section: release-notes
  - section: concepts
  - section: get-started
  - section: use
  - section: support
  - title: 법적 고지
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: 시작하십시오
    links:
    - title: Astra Data Store에 대해 자세히 알아보십시오
      url: "/concepts/intro.html"
    - title: Astra Data Store 미리 보기의 내용
      url: "/release-notes/whats-new.html"
    - title: 시도해 보십시오
      url: "/get-started/install-ads.html#edit-and-apply-the-astra-data-store-license"
    - title: Astra Data Store 미리 보기를 설치합니다
      url: "/get-started/install-ads.html"
    - title: Astra 데이터 저장소 미리 보기를 설정합니다
      url: "/get-started/setup-ads.html"
  - title: Astra Data Store 미리 보기를 사용합니다
    links:
    - title: kubeck 명령으로 관리하십시오
      url: "/use/kubectl-commands-ads.html"
    - title: Cloud Insights를 통해 메트릭을 모니터링합니다
      url: "/use/monitor-with-cloud-insights.html"
    - title: 이벤트 로그를 모니터링합니다
      url: "/use/configure-endpoints.html"
    - title: Astra Control Center 통합
      url: "/use/ads-acc-ui.html"
  - title: 데모 자습서
    links:
    - title: Kubernetes의 미래
      url: https://cloud.netapp.com/astra-data-store
    - title: Astra Data Store 미리보기 데모
      url: https://netapp.hubs.vidyard.com/watch/aDmgkBbJhUTZAGmH5XKimA?
  - title: 블로그 커뮤니티
    links:
    - title: Astra 블로그
      url: https://cloud.netapp.com/blog/topic/astra
    - title: Slack “containers(컨테이너)” 채널을 클릭합니다
      url: https://netapp.io/slack
    - title: 쿠버네티스 허브
      url: https://cloud.netapp.com/kubernetes-hub
    - title: 도움을 받을 수 있는 곳
      url: "/support/get-help.html"
product-family: {}
