---
sidebar: sidebar 
permalink: concepts/architecture.html 
keywords: astra, astra datastore, architecture, deployment, astra data store, kubernetes, netapp, clusters, trident 
summary: Astra Data Store는 독립 실행형 Kubernetes 클러스터에 구축할 수 있습니다. 별도의 클러스터에서 실행 중인 Kubernetes 애플리케이션에 영구 볼륨을 제공할 수도 있고, Kubernetes 클러스터에서 동일한 노드 풀에 다른 앱을 호스팅하거나, Kubernetes 클러스터에서 다른 노드 풀에 앱을 호스팅할 수도 있습니다. 
---
= Astra Data Store 구축 모델을 미리 봅니다
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/concepts/


Astra Data Store Preview는 Kubernetes로 구축 및 오케스트레이션된 애플리케이션을 사용하여 호스트에서 스토리지 드라이브를 직접 관리합니다.

다음 옵션 중 하나를 사용하여 베어 메탈 또는 가상 서버에 Astra Data Store 미리 보기를 설치할 수 있습니다.

* 독립 실행형 전용 Kubernetes 클러스터에 구축하여 별도의 클러스터(독립 실행형 클러스터)에서 실행 중인 Kubernetes 애플리케이션에 영구 볼륨을 제공합니다.
* Kubernetes 클러스터에 구축할 경우 동일한 노드 풀(통합 클러스터)에서 다른 워크로드 애플리케이션을 호스팅할 수 있습니다.
* Kubernetes 클러스터에 구축할 경우 다른 노드 풀(disaggregated 클러스터)에서 다른 워크로드 애플리케이션을 호스팅할 수도 있습니다.


link:../get-started/requirements.html["Astra Data Store 하드웨어 요구 사항에 대해 자세히 알아보십시오"].

Astra Data Store Preview는 Astra 제품군의 일부입니다. Astra 제품군 전체를 보려면 을 참조하십시오 https://docs.netapp.com/us-en/astra-family/intro-family.html["Astra 제품군 소개"^].



== Astra Data Store 미리 보기 에코시스템

Astra Data Store 미리 보기는 다음과 같이 작동합니다.

* * Astra Control Center *: 사내 환경에서 Kubernetes 클러스터의 애플리케이션 인식 데이터 관리를 위해 Astra Control Center 소프트웨어를 사용합니다. Kubernetes 앱을 손쉽게 백업하고, 데이터를 다른 클러스터로 마이그레이션하고, 작동하는 애플리케이션 클론을 즉시 생성할 수 있습니다.
+
Astra Control Center는 ONTAP 또는 Astra Data Store 미리 보기 스토리지 백엔드가 포함된 Astra Trident 스토리지 백엔드를 포함하는 OpenShift Kubernetes 클러스터를 지원합니다.

* * Astra Trident *: NetApp에서 관리하는 완전 지원되는 오픈 소스 스토리지 공급자 및 오케스트레이터로서, Astra Trident를 사용하면 Docker 및 Kubernetes에서 관리하는 컨테이너 형태의 애플리케이션용 스토리지 볼륨을 생성할 수 있습니다.
+
Astra Trident를 사용하여 Astra Data Store 미리 보기에서 볼륨을 생성합니다.

* * Cloud Insights *: NetApp 클라우드 인프라 모니터링 툴인 Cloud Insights를 사용하면 Astra Control에서 관리하는 Kubernetes 클러스터의 성능과 활용률을 모니터링할 수 있습니다. Cloud Insights는 스토리지 사용량과 워크로드를 상호 연관시킵니다.
+
Astra Control에서 Cloud Insights 연결을 활성화하면 Astra Control UI 페이지에 원격 측정 정보가 표시됩니다. Cloud Insights는 Astra 데이터 저장소 미리 보기에서 관리되는 리소스에 대한 정보를 표시합니다.





== Astra Data Store 미리 보기 인터페이스

다른 인터페이스를 사용하여 작업을 완료할 수 있습니다.

* * 웹 UI(사용자 인터페이스) *: Astra Control Service와 Astra Control Center는 앱을 관리, 마이그레이션 및 보호할 수 있는 동일한 웹 기반 UI를 사용합니다. 이 UI에는 Astra Data Store 미리 보기 볼륨에 대한 정보도 표시됩니다.
* * API *: Astra Control Service와 Astra Control Center는 동일한 Astra Control API를 사용합니다. API를 사용하면 UI를 사용할 때와 동일한 작업을 수행할 수 있습니다. Astra Control API를 사용하여 Astra Data Store 미리 보기에 대한 정보를 검색할 수도 있습니다.
* * kubbtl 명령 *: Astra Data Store 미리 보기와 함께 사용하려면 kudeck 명령을 직접 사용할 수 있습니다.
* * Kubernetes 확장 *: 또한 Astra Data Store 미리보기 Kubernetes API 확장을 사용할 수 있습니다.
+
사용자 정의 리소스 정의(CRD)는 Astra Data Store 미리보기 운영자가 구축할 때 생성되는 Kubernetes REST API의 확장입니다. 외부 엔터티는 Kubernetes API 서버를 호출하여 CRD와 상호 작용합니다. Astra Data Store 미리 보기는 특정 CRD에 대한 업데이트를 확인한 다음 내부 REST API를 호출합니다.





== 를 참조하십시오

* https://docs.netapp.com/us-en/astra-family/intro-family.html["Astra 제품군 소개"^]
* https://docs.netapp.com/us-en/astra/index.html["Astra Control Service 문서"^]
* https://docs.netapp.com/us-en/astra-control-center/["Astra Control Center 문서"^]
* https://docs.netapp.com/us-en/trident/index.html["Astra Trident 문서"^]
* https://docs.netapp.com/us-en/astra-automation/index.html["Astra Control API를 사용합니다"^]
* https://docs.netapp.com/us-en/cloudinsights/["Cloud Insights 설명서"^]
* https://docs.netapp.com/us-en/ontap/index.html["ONTAP 설명서"^]

