---
sidebar: sidebar 
permalink: use/maintain-cluster.html 
keywords: astra, astra data store, kubectl 
summary: Astra Data Store에서 kubtl 명령을 사용하여 클러스터를 유지 관리할 수 있습니다. 
---
= 클러스터를 관리합니다
:hardbreaks:
:icons: font
:imagesdir: ../media/use/


Astra Data Store 미리 보기와 함께 kubtl 명령을 사용하여 클러스터를 관리할 수 있습니다.

* <<Add a node>>
* <<Place a node in maintenance mode>>
* <<Replace a node>>
* <<Replace a drive>>


.무엇을 &#8217;필요로 할거야
* kubctl 및 kubbctl-astrads 플러그인이 설치된 시스템. 을 참조하십시오 link:../get-started/install-ads.html["Astra Data Store 미리 보기를 설치합니다"].




== 노드를 추가합니다

추가하려는 노드는 Kubernetes 클러스터의 일부여야 하며 클러스터의 다른 노드와 비슷한 구성을 가져야 합니다.

.단계
. 새 노드의 데이터 IP가 ADSCluster CR에 아직 포함되지 않은 경우 다음을 수행합니다.
+
.. astradscluster CR을 편집하고 ADS 데이터 네트워크 주소 필드에 추가 데이터 IP를 추가합니다.
+
[listing]
----
~% kubectl edit astradscluster <cluster-name> -n astrads-system
----
+
응답:

+
[listing]
----
ADS Data Networks:
    Addresses:  dataIP1, dataIP2, dataIP3, dataIP4, *newdataIP*
----
.. CR 파일을 저장합니다.
.. Astra Data Store 미리 보기 클러스터에 노드를 추가합니다.
+
[listing]
----
~% kubectl astrads nodes add –cluster <cluster-name>
----


. 그렇지 않으면 노드를 추가하기만 하면 됩니다.
+
[listing]
----
~% kubectl astrads nodes add –cluster <cluster-name>
----
. 노드가 추가되었는지 확인합니다.
+
[listing]
----
~% kubectl astrads nodes list
----




== 노드를 유지보수 모드로 전환합니다

호스트 유지보수 또는 패키지 업그레이드를 수행해야 하는 경우 노드를 유지보수 모드로 전환해야 합니다.


NOTE: 노드는 이미 Astra Data Store 미리 보기 클러스터에 포함되어 있어야 합니다.

노드가 유지보수 모드일 때는 클러스터에 노드를 추가할 수 없습니다. 이 예제에서는 노드 "nhcitj1525"를 유지 관리 모드로 설정합니다.

.단계
. 노드 세부 정보를 표시합니다.
+
[listing]
----
~% kubectl get nodes
----
+
응답:

+
[listing]
----
 NAME             STATUS   ROLES                  AGE     VERSION
 nhcitjj1525      Ready    <none>                 3d18h   v1.20.0
 nhcitjj1526      Ready    <none>                 3d18h   v1.20.0
 nhcitjj1527      Ready    <none>                 3d18h   v1.20.0
 nhcitjj1528      Ready    <none>                 3d18h   v1.20.0
 scs000039783-1   Ready    control-plane,master   3d18h   v1.20.0
----
. 노드가 유지보수 모드가 아닌지 확인합니다.
+
[listing]
----
~% kubectl astrads maintenance list
----
+
응답(유지보수 모드에 있는 노드가 이미 없음):

+
[listing]
----
NAME    NODE NAME  IN MAINTENANCE  MAINTENANCE STATE       MAINTENANCE VARIANT
----
. 유지보수 모드를 활성화합니다.
+
[listing]
----
~% kubectl astrads maintenance create <cr-name> --node-name=<<node-name>> --variant=Node
----
+
샘플:

+
[listing]
----
~% kubectl astrads maintenance create maint1 --node-name="nhcitjj1525" --variant=Node
Maintenance mode astrads-system/maint1 created
----
. 노드를 나열합니다.
+
[listing]
----
~% kubectl astrads nodes list
----
+
응답:

+
[listing]
----
NODE NAME       NODE STATUS     CLUSTER NAME
nhcitjj1525     Added           ftap-astra-012
...
----
. 유지보수 모드의 상태를 점검합니다.
+
[listing]
----
~% kubectl astrads maintenance list
----
+
응답:

+
[listing]
----
NAME    NODE NAME       IN MAINTENANCE  MAINTENANCE STATE       MAINTENANCE VARIANT
node4   nhcitjj1525     true            ReadyForMaintenance     Node
----
+
유지보수 모드는 거짓으로 시작해 참으로 바뀝니다. 유지 보수 상태가 PreparingForMaintenance에서 ReadyforMaintenance로 바뀝니다.

. 노드 유지보수가 완료된 후 유지보수 모드를 비활성화합니다.
+
[listing]
----
~% kubectl astrads maintenance update maint1 --node-name="nhcitjj1525" --variant=None
----
. 노드가 더 이상 유지보수 모드가 아닌지 확인합니다.
+
[listing]
----
~% kubectl astrads maintenance list
----




== 노드를 교체합니다

Astra Data Store 미리 보기와 함께 kubtl 명령을 사용하여 클러스터에서 장애가 발생한 노드를 교체합니다.

.단계
. 모든 노드 나열:
+
[listing]
----
~% kubectl astrads nodes list
----
+
응답:

+
[listing]
----
NODE NAME           NODE STATUS    CLUSTER NAME
sti-rx2540-534d..   Added       cluster-multinodes-21209
sti-rx2540-535d...  Added       cluster-multinodes-21209
...
----
. 클러스터 설명:
+
[listing]
----
~% kubectl astrads clusters list
----
+
응답:

+
[listing]
----
CLUSTER NAME               CLUSTER STATUS  NODE COUNT
cluster-multinodes-21209   created         4
----
. 노드 HA가 장애가 발생한 노드에서 FALSE로 표시되는지 확인합니다.
+
[listing]
----
~% kubectl describe astradscluster -n astrads-system
----
+
응답:

+
[listing]
----
Name:         cluster-multinodes-21209
Namespace:    astrads-system
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"astrads.netapp.io/v1alpha1","kind":"AstraDSCluster","metadata":{"annotations":{},"name":"cluster-multinodes-21209","namespa...
API Version:  astrads.netapp.io/v1alpha1
Kind:         AstraDSCluster

State:               Disabled
Variant:             None
Node HA:             false
Node ID:             4
Node Is Reachable:   false
Node Management IP:  172.21.192.192
Node Name:           sti-rx2540-532d.ctl.gdl.englab.netapp.com
Node Role:           Storage
Node UUID:           6f6b88f3-8411-56e5-b1f0-a8e8d0c946db
Node Version:        12.75.0.6167444
Status:              Added
----
. "AdsNode Count"의 값을 3으로 감소함으로써 실패한 노드를 제거하도록 Asta클러스터 CR을 수정합니다.
+
[listing]
----
cat manifests/astradscluster.yaml
----
+
응답:

+
[listing]
----
apiVersion: astrads.netapp.io/v1alpha1
kind: AstraDSCluster
metadata:
  name: cluster-multinodes-21209
  namespace: astrads-system
spec:
  # ADS Node Configuration per node settings
  adsNodeConfig:
    # Specify CPU limit for ADS components
    # Supported value: 9
    cpu: 9
    # Specify Memory Limit in GiB for ADS Components.
    # Your kubernetes worker nodes need to have at least this much RAM free
    # for ADS to function correctly
    # Supported value: 34
    memory: 34
    # [Optional] Specify raw storage consumption limit. The operator will only select drives for a node up to this limit
    capacity: 600
    # [Optional] Set a cache device if you do not want auto detection e.g. /dev/sdb
    # cacheDevice: ""
    # Set this regex filter to select drives for ADS cluster
    # drivesFilter: ".*"

  # [Optional] Specify node selector labels to select the nodes for creating ADS cluster
  # adsNodeSelector:
  #   matchLabels:
  #     customLabelKey: customLabelValue

  # Specify the number of nodes that should be used for creating ADS cluster
  adsNodeCount: 3

  # Specify the IP address of a floating management IP routable from any worker node in the cluster
  mvip: "172..."

  # Comma separated list of floating IP addresses routable from any host where you intend to mount a NetApp Volume
  # at least one per node must be specified
  # addresses: 10.0.0.1,10.0.0.2,10.0.0.3,10.0.0.4,10.0.0.5
  # netmask: 255.255.255.0
  adsDataNetworks:
    - addresses: "172..."
      netmask: 255.255.252.0


  # [Optional] Provide a k8s label key that defines which protection domain a node belongs to
  # adsProtectionDomainKey: ""

  # [Optional] Provide a monitoring config to be used to setup/configure a monitoring agent.
  monitoringConfig:
   namespace: "netapp-monitoring"
   repo: "docker.repo.eng.netapp.com/global/astra"

  autoSupportConfig:
    # AutoUpload defines the flag to enable or disable AutoSupport upload in the cluster (true/false)
    autoUpload: true
    # Enabled defines the flag to enable or disable automatic AutoSupport collection.
    # When set to false, periodic and event driven AutoSupport collection would be disabled.
    # It is still possible to trigger an AutoSupport manually while AutoSupport is disabled
    # enabled: true
    # CoredumpUpload defines the flag to enable or disable the upload of coredumps for this ADS Cluster
    # coredumpUpload: false
    # HistoryRetentionCount defines the number of local (not uploaded) AutoSupport Custom Resources to retain in the cluster before deletion
    historyRetentionCount: 25
    # DestinationURL defines the endpoint to transfer the AutoSupport bundle collection
    destinationURL: "https://testbed.netapp.com/put/AsupPut"
    # ProxyURL defines the URL of the proxy with port to be used for AutoSupport bundle transfer
    # proxyURL:
    # Periodic defines the config for periodic/scheduled AutoSupport objects
    periodic:
      # Schedule defines the Kubernetes Cronjob schedule
      - schedule: "0 0 * * *"
        # PeriodicConfig defines the fields needed to create the Periodic AutoSupports
        periodicconfig:
        - component:
            name: storage
            event: dailyMonitoring
          userMessage: Daily Monitoring Storage AutoSupport bundle
          nodes: all
        - component:
            name: controlplane
            event: daily
          userMessage: Daily Control Plane AutoSupport bundle
----
. 클러스터에서 노드가 제거되었는지 확인합니다.
+
[listing]
----
~% kubectl get nodes --show-labels

----
+
응답:

+
[listing]
----

NAME                  STATUS   ROLES               AGE   VERSION   LABELS
sti-astramaster-237   Ready control-plane,master   24h   v1.20.0
sti-rx2540-532d       Ready  <none>                24h   v1.20.0
sti-rx2540-533d       Ready  <none>                24h
----
+
[listing]
----
~% kubectl astrads nodes list
----
+
응답:

+
[listing]
----
NODE NAME         NODE STATUS     CLUSTER NAME
sti-rx2540-534d   Added           cluster-multinodes-21209
sti-rx2540-535d   Added           cluster-multinodes-21209
sti-rx2540-536d   Added           cluster-multinodes-21209
----
+
[listing]
----
~% kubectl get nodes --show-labels
----
+
응답:

+
[listing]
----
NAME                STATUS   ROLES                  AGE   VERSION   LABELS
sti-astramaster-237 Ready    control-plane,master   24h   v1.20.0   beta.kubernetes.io/arch=amd64,
sti-rx2540-532d     Ready    <none>                 24h   v1.20.0   astrads.netapp.io/node-removal
----
+
[listing]
----
~% kubectl describe astradscluster -n astrads-system
----
+
응답:

+
[listing]
----
Name:         cluster-multinodes-21209
Namespace:    astrads-system
Labels:       <none>
Kind:         AstraDSCluster
Metadata:
...
----
. 클러스터 CR을 수정하여 교체할 노드를 클러스터에 추가합니다. 노드 수는 4까지 증가합니다. 추가를 위해 새 노드가 선택되었는지 확인합니다.
+
[listing]
----
rvi manifests/astradscluster.yaml
cat manifests/astradscluster.yaml
apiVersion: astrads.netapp.io/v1alpha1
kind: AstraDSCluster
metadata:
  name: cluster-multinodes-21209
  namespace: astrads-system
----
+
[listing]
----
~% kubectl apply -f manifests/astradscluster.yaml
----
+
응답:

+
[listing]
----
astradscluster.astrads.netapp.io/cluster-multinodes-21209 configured
----
+
[listing]
----
~% kubectl get pods -n astrads-system
----
+
응답:

+
[listing]
----
NAME                                READY   STATUS    RESTARTS   AGE
astrads-cluster-controller...       1/1     Running   1          24h
astrads-deployment-support...       3/3     Running   0          24h
astrads-ds-cluster-multinodes-21209 1/1     Running
----
+
[listing]
----
~% kubectl astrads nodes list
----
+
응답:

+
[listing]
----
NODE NAME                NODE STATUS     CLUSTER NAME
sti-rx2540-534d...       Added           cluster-multinodes-21209
sti-rx2540-535d...       Added           cluster-multinodes-21209
----
+
[listing]
----
~% kubectl astrads clusters list
----
+
응답:

+
[listing]
----
CLUSTER NAME                    CLUSTER STATUS  NODE COUNT
cluster-multinodes-21209        created         4
----
+
[listing]
----
~% kubectl astrads drives list
----
+
응답:

+
[listing]
----
DRIVE NAME    DRIVE ID    DRIVE STATUS   NODE NAME     CLUSTER NAME
scsi-36000..  c3e197f2... Active         sti-rx2540... cluster-multinodes-21209
----




== 드라이브를 교체합니다

클러스터에서 드라이브가 고장난 경우 데이터 무결성을 보장하기 위해 가능한 한 빨리 드라이브를 교체해야 합니다. 드라이브에 장애가 발생하면 클러스터 CR 노드 상태, 클러스터 상태 정보 및 메트릭 끝점에서 장애가 발생한 드라이브 정보를 볼 수 있습니다.

.노드Statuses.driveStatuses에서 장애가 발생한 드라이브를 표시하는 클러스터의 예
[listing]
----
$ kubectl get adscl -A -o yaml
----
응답:

[listing]
----
...
apiVersion: astrads.netapp.io/v1alpha1
kind: AstraDSCluster
...
nodeStatuses:
  - driveStatuses:
    - driveID: 31205e51-f592-59e3-b6ec-185fd25888fa
      driveName: scsi-36000c290ace209465271ed6b8589b494
      drivesStatus: Failed
    - driveID: 3b515b09-3e95-5d25-a583-bee531ff3f31
      driveName: scsi-36000c290ef2632627cb167a03b431a5f
      drivesStatus: Active
    - driveID: 0807fa06-35ce-5a46-9c25-f1669def8c8e
      driveName: scsi-36000c292c8fc037c9f7e97a49e3e2708
      drivesStatus: Active
...
----
장애가 발생한 드라이브 CR은 장애가 발생한 드라이브의 UUID에 해당하는 이름으로 클러스터에 자동으로 생성됩니다.

[listing]
----
$ kubectl get adsfd -A -o yaml
----
응답:

[listing]
----
...
apiVersion: astrads.netapp.io/v1alpha1
kind: AstraDSFailedDrive
metadata:
    name: c290a-5000-4652c-9b494
    namespace: astrads-system
spec:
  executeReplace: false
  replaceWith: ""
 status:
   cluster: arda-6e4b4af
   failedDriveInfo:
     failureReason: AdminFailed
     inUse: false
     name: scsi-36000c290ace209465271ed6b8589b494
     path: /dev/disk/by-id/scsi-36000c290ace209465271ed6b8589b494
     present: true
     serial: 6000c290ace209465271ed6b8589b494
     node: sti-rx2540-300b.ctl.gdl.englab.netapp.com
   state: ReadyToReplace
----
[listing]
----
~% kubectl astrads faileddrive list --cluster arda-6e4b4af
----
응답:

[listing]
----
NAME       NODE                             CLUSTER        STATE                AGE
6000c290   sti-rx2540-300b.lab.netapp.com   ard-6e4b4af    ReadyToReplace       13m
----
.단계
. 교체 제한 사항에 맞는 드라이브를 필터링하는 "kubbeck astrads show-replacement" 명령을 사용하여 가능한 교체 드라이브를 나열합니다(클러스터에서 사용되지 않음, 마운트되지 않음, 파티션 없음, 오류가 발생한 드라이브보다 크거나 같음).
+
가능한 대체 드라이브를 필터링하지 않고 모든 드라이브를 나열하려면 'show-replacement' 명령에 '--all'을 추가합니다.

+
[listing]
----
~%  kubectl astrads faileddrive show-replacements --cluster ard-6e4b4af --name 6000c290
----
+
응답:

+
[listing]
----
NAME  IDPATH             SERIAL  PARTITIONCOUNT   MOUNTED   SIZE
sdh   /scsi-36000c29417  45000c  0                false     100GB
----
. "replace" 명령을 사용하여 드라이브를 전달된 일련 번호로 교체합니다. 명령이 대체를 완료하거나, '--wait' 시간이 경과되면 실패합니다.
+
[listing]
----
~% kubectl astrads faileddrive replace --cluster arda-6e4b4af --name 6000c290 --replaceWith 45000c --wait
Drive replacement completed successfully
----
+

NOTE: 부적절한 일련 번호를 사용하여 kubbtl astrads faileddrive replace를 실행하면 다음과 같은 오류가 나타납니다.

+
[listing]
----
~% kubectl astrads replacedrive replace --cluster astrads-cluster-f51b10a --name 6000c2927 --replaceWith BAD_SERIAL_NUMBER
Drive 6000c2927 replacement started
Failed drive 6000c2927 has been set to use BAD_SERIAL_NUMBER as a replacement
...
Drive replacement didn't complete within 25 seconds
Current status: {FailedDriveInfo:{InUse:false Present:true Name:scsi-36000c2 FiretapUUID:444a5468 Serial:6000c Path:/scsi-36000c FailureReason:AdminFailed Node:sti-b200-0214a.lab.netapp.com} Cluster:astrads-cluster-f51b10a State:ReadyToReplace Conditions:[{Message: "Replacement drive serial specified doesn't exist", Reason: "DriveSelectionFailed", Status: False, Type:' Done"]}
----
. 드라이브 교체를 다시 실행하려면 이전 명령으로 '--force'를 사용하십시오.
+
[listing]
----
~%  kubectl astrads replacedrive replace --cluster astrads-cluster-f51b10a --name 6000c2927 --replaceWith VALID_SERIAL_NUMBER --force
----




== 를 참조하십시오

* link:../use/kubectl-commands-ads.html["kubctl 명령을 사용하여 Astra Data Store 미리 보기 자산을 관리합니다"]

