---
sidebar: sidebar 
permalink: use/monitor-with-prometheus-grafana.html 
keywords: astra, astra data store, kubectl, endpoints, prometheus, grafana, visualization 
summary: Prometheus 및 Grafana를 사용하여 Astra Data Store 자산을 모니터링할 수 있습니다. 
---
= Prometheus 및 Grafana를 사용하여 메트릭을 모니터링합니다
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


Prometheus 및 Grafana를 사용하여 Astra Data Store 미리보기 메트릭을 모니터링할 수 있습니다. Ameta Data Store 미리보기 Kubernetes 클러스터 메트릭 엔드포인트에서 메트릭을 수집하도록 Prometheus를 구성할 수 있으며 Grafana를 사용하여 메트릭 데이터를 시각화할 수 있습니다.

.무엇을 &#8217;필요로 할거야
* Astra Data Store 미리 보기 클러스터 또는 Astra Data Store 미리 보기 클러스터와 통신할 수 있는 다른 클러스터에 Prometheus 및 Grafana 패키지를 다운로드하여 설치했는지 확인합니다. 공식 설명서의 지침에 따라 각 도구를 설치합니다.
+
** https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Astra/How_to_deploy_Prometheus_with_Astra_Data_Store["Prometheus를 설치합니다"^]
** https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Astra/How_to_set_up_Grafana_for_monitoring_Astra_Data_Store_cluster["Grafana를 설치합니다"^]


* Prometheus 및 Grafana는 Astra Data Store 미리보기 Kubernetes 클러스터와 통신할 수 있어야 합니다. Prometheus와 Grafana가 Astra Data Store 미리보기 클러스터에 설치되어 있지 않은 경우, Astra Data Store 미리보기 클러스터에서 실행 중인 메트릭 서비스와 통신할 수 있는지 확인해야 합니다.




== Prometheus를 구성합니다

Astra Data Store Preview는 Kubernetes 클러스터의 TCP 포트 9341에 메트릭 서비스를 노출합니다. 이 서비스에서 메트릭을 수집하려면 Prometheus를 구성해야 합니다.

.단계
. Prometheus 설치를 위해 'Prometheus.yml' 설정 파일을 편집합니다.
. Astra Data Store 미리 보기 서비스 이름 및 해당 포트를 가리키는 서비스 목표를 추가합니다. 예를 들면 다음과 같습니다.
+
[listing]
----
scrape_configs:
static_configs:
- targets: ['astrads-metrics-service.astrads-system:9341']
----
. Prometheus 서비스를 시작합니다.




== Grafana 구성

Grafana를 구성하여 Prometheus에서 수집한 메트릭을 표시할 수 있습니다.

.단계
. Grafana 설치를 위해 'datasources.yAML' 구성 파일을 편집합니다.
. Prometheus를 데이터 소스로 추가합니다. 예를 들면 다음과 같습니다.
+
[listing]
----
apiVersion: 1

datasources:
  - name: astradatastore-prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090
    jsonData:
      manageAlerts: false
----
. Grafana 서비스를 시작합니다.
. 에 대한 Grafana 설명서의 지침을 따릅니다 https://grafana.com/docs/grafana/latest/getting-started/getting-started/["시작하십시오"^].




== Grafana 대시보드 템플릿을 가져옵니다

Astra Data Store 미리 보기를 설치하기 위해 다운로드한 번들 파일에는 Grafana 내에서 가져올 수 있는 Grafana 대시보드 템플릿 파일이 포함되어 있습니다. 이러한 대시보드 템플릿을 사용하면 Astra Data Store 미리 보기에서 사용할 수 있는 메트릭의 유형과 이를 보는 방법을 확인할 수 있습니다.

.단계
. Astra Data Store preview '.tar.gz' bundle을 엽니다.
. 'manifests' 디렉터리를 엽니다.
. graana_cluster.json과 graana_volume.json 파일을 추출한다.
. Grafana 웹 UI 사용, https://grafana.com/docs/grafana/latest/dashboards/export-import/["에서 대시보드 템플릿 파일을 Grafana로 가져옵니다"^].

