---
sidebar: sidebar 
permalink: get-started/faq-ads.html 
keywords: faq, frequently asked questions, astra, astra data store, kubernetes, persistent volumes 
summary: 이 FAQ는 질문에 대한 간단한 답변을 찾는 경우에 도움이 될 수 있습니다. 
---
= Astra Data Store 미리 보기를 위한 질문과 대답
:hardbreaks:
:icons: font
:imagesdir: ../media/


Astra Data Store 미리 보기의 설치, 구성, 업그레이드 및 문제 해결에 대해 자주 묻는 질문에 대한 답변을 찾아보십시오.



== 일반적인 질문

* 생산에 Astra Data Store 미리보기를 사용할 수 있습니까? * 아니요 Astra Data Store는 엔터프라이즈급 복구 성능을 제공하도록 설계 및 개발되었지만, 미리 보기 릴리즈인 Astra Data Store Preview는 운영 워크로드를 대상으로 하지 않습니다.

* 가상 머신 워크로드에 Astra Data Store 미리보기를 사용할 수 있습니까? * Astra Data Store 미리보기 릴리즈는 베어 메탈 또는 가상 머신에서 실행 중인 애플리케이션에만 한정됩니다. 향후 릴리즈에서는 Kubernetes 및 ESXi 가상 머신 모두에서 애플리케이션을 직접 지원합니다. 을 참조하십시오 link:../get-started/requirements.html["Astra 데이터 저장소 요구 사항"].

* Astra Data Store 미리 보기에는 다른 NetApp 제품의 기능에 대한 의존성이 있습니까? *

예. Astra Data Store 미리 보기를 사용하려면 NetApp CSI 드라이버 Astra Trident 버전 21.10.1 이상이 워크로드 Kubernetes 클러스터에 배포되어야 합니다. 에 대해 자세히 알아보십시오 link:../get-started/requirements.html["Astra 데이터 저장소 요구 사항"].

Astra Data Store Preview 클러스터를 스토리지 백엔드로 사용하는 애플리케이션은 를 사용할 수 있습니다 https://docs.netapp.com/us-en/astra-control-center/index.html["Astra 제어 센터"^] 버전 21.12를 사용하여 Kubernetes 워크로드의 데이터 보호, 재해 복구, 마이그레이션을 비롯한 애플리케이션 인식 데이터 관리 기능을 활용할 수 있습니다.

* Astra Data Store 미리보기 클러스터를 관리하려면 어떻게 해야 합니까? * kubtl 명령을 사용하거나 Kubernetes API 확장을 사용하여 Astra Data Store 미리보기 자산을 관리할 수 있습니다.

kubbeck astrads 명령어에는 편의에 따라 사용 및 플래그 문서를 제공하는 '-h' 스위치가 포함되어 있습니다.

* Astra 데이터 저장소 미리 보기 클러스터 메트릭을 어떻게 모니터링할 수 있습니까? * Cloud Insights를 사용하여 Astra 데이터 저장소 미리 보기 메트릭을 모니터링할 수 있습니다. 을 참조하십시오 link:../use/monitor-with-cloud-insights.html["Cloud Insights를 통해 메트릭을 모니터링합니다"].

로그를 모니터링할 수도 있습니다. 을 참조하십시오 link:../use/configure-endpoints.html["이벤트 로그를 구성하고 모니터링합니다"].

* Kubernetes 클러스터의 ONTAP 또는 다른 스토리지 공급자와 함께 Astra Data Store 미리보기를 사용할 수 있습니까? * 예. Astra Data Store 미리 보기는 애플리케이션 클러스터의 다른 스토리지 공급자와 함께 사용할 수 있습니다.

* Astra 데이터 저장소 미리 보기에서 Kubernetes 클러스터를 제거하면 Astra Trident가 제거됩니까? * Astra 데이터 저장소 미리 보기를 제거하면 Astra Trident가 클러스터에서 제거되지 않습니다. Astra Trident를 제거해야 하는 경우 별도로 제거해야 합니다.



== 라이센싱

* Astra Data Store 미리 보기에는 라이센스가 필요합니까? * 예, Astra Data Store 미리 보기를 사용하려면 NetApp 라이센스 파일(NLF)이 필요합니다.

을 참조하십시오 link:../get-started/requirements.html["Astra 데이터 저장소 요구 사항"].

* Astra 데이터 저장소 미리 보기 라이센스는 얼마나 유효합니까? * Astra 데이터 저장소 미리 보기 라이센스의 기본 기간은 다운로드 날짜로부터 90일입니다.



== Kubernetes 클러스터에서 Astra Data Store 미리 보기의 설치 및 사용

* 베어 메탈 또는 가상 머신에서 실행 중인 Kubernetes 클러스터에 Astra Data Store 미리보기를 설치할 수 있습니까? * 예. Astra Data Store 미리 보기는 베어 메탈 또는 ESXi VM에서 실행되는 Kubernetes 클러스터에 설치할 수 있습니다. 을 참조하십시오 link:../get-started/requirements.html["Astra Data Store 미리 보기 요구 사항"].

* Astra Data Store Preview용 Kubernetes의 지원되는 버전은 무엇입니까? *

Astra Data Store 미리 보기는 v1.20 이상과 호환되는 Kubernetes 배포판과 연동됩니다. 그러나 현재 일부 Kubernetes 배포에서 검증되지 않았습니다. 에 대해 자세히 알아보십시오 link:../get-started/requirements.html["Astra Data Store 미리 보기 요구 사항"].

* My Kubernetes 클러스터가 5개 이상의 작업자 노드입니다. Astra 데이터 저장소 미리 보기를 설치할 수 있습니까? * 예. Kubernetes 클러스터의 4개 작업자 노드에 Astra Data Store 미리보기 클러스터를 구축할 수 있습니다. 구축한 후에는 클러스터를 5개의 작업자 노드로 확장할 수 있습니다.

* Astra 데이터 저장소 미리 보기는 개인 레지스트리의 오프라인 설치를 지원합니까? * 예. Astra Data Store 미리 보기는 로컬 레지스트리에서 오프라인으로 설치할 수 있습니다. 을 참조하십시오 link:../get-started/install-ads.html["Astra Data Store 미리 보기를 설치합니다"]. 그러나 Astra Data Store 미리 보기를 사용하려면 NetApp AutoSupport 백엔드(support.netapp.com 직접 또는 프록시를 통해 연결해야 합니다.

* Astra 데이터 저장소 미리 보기를 사용하려면 인터넷 연결이 필요합니까? * Astra 데이터 저장소 미리 보기를 사용하려면 NetApp AutoSupport 백엔드에 연결해야 필수 원격 측정 AutoSupport 번들을 정기적으로 보낼 수 있습니다. 이러한 연결은 직접 또는 프록시를 통해 가능합니다. 이 연결이 없거나 AutoSupport가 비활성화된 경우 클러스터가 잠기며 주기적인 번들 업로드가 재개될 때까지 새 볼륨 생성이 비활성화됩니다.

* Astra Data Store Preview에서 사용하는 역할과 권한은 무엇입니까? * Astra Data Store Preview 운영자를 배포하려면 kudo 관리자여야 합니다.

Astra Data Store Preview에는 노드 선택에 사용되는 노드 리소스를 검색하는 데 사용되는 "astrads-ds-nodeinfo-astradsversion"이라는 특별한 데모가 포함되어 있습니다.

또한 운영자는 권한이 있는 Kubernetes 작업을 사용하여 선택한 작업자 노드에 스토리지 클러스터의 컨테이너를 설치하여 Astra Data Store 미리 보기 스토리지 클러스터를 구축합니다.

* Astra Data Store 미리 보기 설치를 위해 업데이트해야 하는 매니페스트 파일은 무엇입니까? * 에서 다운로드한 Astra Data Store 미리 보기 번들에서 다운로드할 수 있습니다 https://mysupport.netapp.com/site/products/all/details/astra-data-store/downloads-tab["NetApp Support 사이트"^], 다음과 같은 매니페스트가 제공됩니다.

* Astasscluster.YAML
* Astassoperator.YAML
* Astradsversion.YAML을 참조하십시오
* monitoring_operator.YAML


배포별 구성으로 "astradscluster.yaML" 매니페스트를 업데이트해야 합니다. 을 참조하십시오 link:../get-started/install-ads.html["Astra Data Store 미리 보기를 설치합니다"].



== 문제 해결 및 지원

Astra Data Store 미리 보기를 사용하면 NetApp Containers Slack 채널을 사용하여 커뮤니티 지원에 액세스할 수 있습니다. 이 채널은 NetApp Support 및 기술 마케팅 엔지니어가 모니터링합니다.

https://netapp.io/slack["NetApp 컨테이너 여유 채널"^]

Preview 릴리즈를 사용하려면 시스템이 클라우드에 연결되고 NetApp Active IQ 및 AutoSupport 도구에 통합되어 있어야 합니다.

을 참조하십시오 link:../support/get-help-ads.html["Astra Data Store 지원 작업"].

* 지원 케이스를 제출하거나 빠른 질문에 대한 명확한 설명을 요청하는 방법은 무엇입니까? * 지원 케이스를 제출하거나 빠른 질문에 대한 설명을 받으려면 에 대해 문제나 질문을 신고하십시오 https://netapp.io/slack["NetApp 컨테이너 여유 채널"^]. NetApp Support는 최선의 노력을 통해 최선의 지원을 제공합니다.

* 새 기능에 대한 요청을 어떻게 제기합니까? * 지원되는 구성 또는 기능에 대한 질문이 있는 경우 astra.feedback@netapp.com 으로 문의하십시오.

* 지원 로그 번들을 생성하려면 어떻게 합니까? * 를 참조하십시오 link:../support/get-help-ads.html#generate-support-bundle-to-provide-to-netapp-support["지원 번들을 생성합니다"] Astra Data Store 미리 보기를 위한 지원 로그 번들을 설정 및 다운로드하는 방법에 대한 지침은 을 참조하십시오.

* Astra Data Store 미리 보기에서 내 Kubernetes 노드를 찾을 수 없습니다. 이 문제를 해결하려면 어떻게 합니까? * 를 참조하십시오 link:../get-started/install-ads.html["Astra Data Store 미리 보기를 설치합니다"].

* IPv6 주소를 관리, 데이터 및 클러스터 네트워크에 사용할 수 있습니까? * 아니요. Astra Data Store 미리 보기는 IPv4 주소만 지원합니다. IPv6 지원은 Astra Data Store Preview의 향후 릴리스에 추가될 예정입니다.

* Astra Data Store 미리 보기에서 볼륨을 프로비저닝하는 동안 어떤 NFS 버전이 사용됩니까? * 기본적으로 Astra Data Store 미리 보기는 Kubernetes 애플리케이션에 프로비저닝된 모든 볼륨에 대해 NFS v4.1을 지원합니다.

* 대용량 드라이브를 사용하여 Astra Data Store 미리보기를 구성한 경우에도 더 큰 영구 볼륨을 얻을 수 없는 이유는 무엇입니까? * Astra Data Store 미리 보기는 노드의 모든 볼륨에 대해 프로비저닝된 최대 용량을 1TiB로 제한하고 Astra Data의 모든 노드에서 최대 5TiB로 제한합니다 Store preview cluster(미리보기 클러스터 저장)

을 참조하십시오 link:../get-started/requirements.html["Astra Data Store 미리 보기 요구 사항"].



== Astra Data Store 미리 보기를 업그레이드하는 중입니다

* Astra Data Store Preview 릴리스에서 업그레이드할 수 있습니까? * 아니요 Astra Data Store 미리 보기는 운영 작업 부하가 아니며, Astra Data Store 미리 보기 소프트웨어의 새 릴리즈에는 새로 설치해야 합니다.
