---
sidebar: sidebar 
permalink: get-started/requirements.html 
keywords: kubernetes cluster, cluster requirements, version requirements, supported versions, apps, supported apps, mariadb, mysql, postgres, kubernetes version, ubuntu, image type, networking 
summary: 먼저 환경에 대한 지원을 확인하십시오. 
---
= Astra Data Store 미리 보기 요구 사항
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


먼저 귀사의 환경이 Astra Data Store 미리 보기 요구 사항을 충족하는지 확인하십시오.

Astra Data Store 프리뷰에서는 베어 메탈과 VM 기반 구축을 모두 지원합니다. Astra Data Store 미리보기 클러스터는 4개 이상의 작업자 노드가 있는 Kubernetes 클러스터에서 실행될 수 있습니다. Astra Data Store 미리보기 소프트웨어는 동일한 Kubernetes 클러스터에서 실행 중인 다른 애플리케이션과 함께 사용할 수 있습니다.

Astra Data Store preview는 Astra Trident CSI 드라이버를 사용하여 Kubernetes 워크로드에 대한 영구 볼륨의 프로비저닝만 지원합니다. VM 워크로드는 Astra Data Store의 향후 릴리스에서 지원됩니다.


NOTE: Astra Control Center에서 Astra Data Store 미리 보기 클러스터를 관리하려는 경우 Astra Data Store 미리 보기 클러스터가 에 맞는지 확인하십시오 https://docs.netapp.com/us-en/astra-control-center/get-started/requirements.html#kubernetes-cluster-general-requirements["Astra Control Center에서 관리할 클러스터에 대한 요구 사항입니다"^] 여기에 설명된 요구 사항 외에



== Kubernetes 작업자 노드 리소스 요구사항

Kubernetes 클러스터의 각 작업자 노드에 있는 Astra Data Store 미리보기 소프트웨어에 할당하기 위해 필요한 리소스 요구사항은 다음과 같습니다.

|===
| 리소스 | 최소 | 최대 


| 데이터 드라이브 수입니다  a| 
* 3(별도의 캐시 디바이스가 있는 경우)
* 4(캐시 디바이스가 없는 경우)

| 14 


| 데이터 드라이브 크기입니다 | 100GiB | 4TiB 


| 선택적 캐시 디바이스의 수입니다 | 1(8GiB 이상 크기) | 해당 없음 


| vCPU 수입니다 | 10 | 10 


| RAM | 35GiB | 35GiB 
|===

NOTE: 최상의 쓰기 성능을 얻으려면 지연 시간이 짧은 전용 고성능 캐시 디바이스를 구성해야 합니다.

각 작업자 노드에는 다음과 같은 추가 요구 사항이 있습니다.

* Astra Data Store 미리 보기 로그 파일을 저장할 호스트 디스크(부팅)의 여유 공간 100GiB 이상
* 클러스터, 데이터 및 관리 트래픽을 위한 최소 1개의 10GbE 또는 더 빠른 네트워크 인터페이스 필요에 따라 추가 1GbE 또는 더 빠른 인터페이스를 사용하여 관리 트래픽을 분리할 수 있습니다.




== 하드웨어 및 소프트웨어 요구 사항

Astra Data Store 미리보기 소프트웨어는 다음과 같은 하드웨어 플랫폼, 소프트웨어 및 스토리지 구성에서 검증되었습니다. 를 방문하십시오 link:../support/get-help-ads.html["NetApp 커뮤니티 지원"] Kubernetes 클러스터 구성이 다른 경우

.하드웨어 플랫폼
* HPE DL360
* HPE DL380
* Dell R640
* Dell R740


Astra Data Store 미리 보기는 다음 드라이브 유형으로 검증되었습니다.

* * 베어 메탈 배포 *: 하이퍼바이저 없이 Kubernetes 클러스터에 직접 설치된 Astra Data Store 미리보기
+
** SATA 또는 NVMe TLC SSD


* * VM 기반 구축 *: ESXi 클러스터에서 호스팅되는 Linux VM의 Kubernetes 클러스터에 설치된 Astra Data Store 미리보기
+
** SATA, SAS 또는 NVMe TLC SSD 기반 데이터 저장소
** 드라이브가 가상 디스크 또는 패스스루 드라이브로 표시됩니다





NOTE: 호스트에서 하드웨어 RAID 컨트롤러 뒤에 SSD를 사용하는 경우 "통과" 모드를 사용하도록 하드웨어 RAID 컨트롤러를 구성합니다.


NOTE: 각 드라이브에는 고유한 일련 번호가 있어야 합니다. VM 생성 시 가상 머신 고급 설정에 disk.enableuid=true 속성을 추가합니다.

.소프트웨어
* 하이퍼바이저: Astra Data Store 미리 보기는 ESXi 7.0을 사용하는 VMware 기반 VM 배포를 통해 검증되었습니다. KVM 기반 배포는 Astra Data Store 미리 보기에서 지원되지 않습니다.
* Astra Data Store 미리 보기는 다음 호스트 운영 체제에서 검증되었습니다.
+
** Red Hat Enterprise Linux 8.4
** Red Hat Enterprise Linux 8.2
** Red Hat Enterprise Linux 7.9
** Red Hat Enterprise Linux CoreOS(RHCOS)
** CentOS 8
** Ubuntu 20.04


* Astra Data Store Preview는 다음 Kubernetes 배포를 통해 검증되었습니다.
+
** Red Hat OpenShift 4.7
** Google Anthos 1.7
** Kubernetes 1.21
** Kubernetes 1.20





NOTE: Astra Data Store 미리 보기를 사용하려면 스토리지 프로비저닝 및 오케스트레이션을 위해 Astra Trident 버전 21.10.1이 필요합니다. 를 참조하십시오 link:setup-ads.html#install-astra-trident["Astra Trident 설치 지침"].



== 네트워킹 요구 사항

Astra Data Store 미리 보기를 사용하려면 클러스터당 IP 주소가 하나씩 필요합니다. MIP와 동일한 서브넷에서 사용되지 않거나 구성되지 않은 IP 주소여야 합니다. Astra Data Store 미리 보기 관리 인터페이스는 Kubernetes 노드의 관리 인터페이스와 동일해야 합니다.

또한 다음 표에 설명된 대로 각 노드를 구성할 수 있습니다.


NOTE: 이 표에는 MIP: 관리 IP 주소 CIP: 클러스터 IP 주소 MVIP: 관리 가상 IP 주소가 사용됩니다

|===
| 구성 | IP 주소가 필요합니다 


| 노드당 1개의 네트워크 인터페이스  a| 
* 노드당 2개:
+
** MIP/CIP: 노드당 관리 인터페이스에서 사전 구성된 IP 주소 1개
** 데이터 IP: MIP와 동일한 서브넷의 노드당 사용되지 않거나 구성되지 않은 IP 주소 1개






| 노드당 2개의 네트워크 인터페이스  a| 
* 노드당 3개:
+
** MIP: 노드당 관리 인터페이스에 사전 구성된 IP 주소 1개
** CIP: MIP와 다른 서브넷의 노드별 데이터 인터페이스에 사전 구성된 IP 주소 1개
** 데이터 IP: CIP와 동일한 서브넷에 있는 노드당 사용되지 않거나 구성되지 않은 IP 주소 1개




|===

NOTE: 클러스터 사용자 지정 리소스(CR) 파일, "astradscluster.yaML"에서 이 두 가지 구성에 대해 데이터 네트워크 게이트웨이 필드를 생략해야 합니다. 각 노드의 기존 라우팅 구성은 모든 주소를 수용한다.


NOTE: 이러한 구성에는 VLAN 태그가 사용되지 않습니다.



== 아스트라 트리덴트

Astra Data Store 미리보기를 사용하려면 애플리케이션 Kubernetes 클러스터가 Astra Trident 21.10.1을 실행해야 합니다. Astra Data Store 미리 보기는 로 구성할 수 있습니다 link:../get-started/setup-ads.html#set-up-astra-data-store-as-storage-backend["스토리지 백엔드"] Astra Trident를 사용하여 영구 볼륨 프로비저닝



== CNI 구성

Astra Data Store 미리 보기는 다음 CNIs를 사용하여 검증되었습니다.

* 바닐라 Kubernetes 클러스터용 Calico 및 Weave Net CNIs
* Red Hat OpenShift Container Platform(OCP)용 OpenShift SDN
* Google Anthos의 Cilium


이러한 CNIs를 사용하려면 호스트 방화벽(firwalld)을 비활성화해야 합니다.



== 지속적인 볼륨 공유 요구 사항

각 Astra Data Store Preview 클러스터는 영구 볼륨을 사용하여 해당 클러스터에 설치된 애플리케이션의 스토리지 요구 사항을 해결할 수 있도록 지원합니다. Kubernetes 앱은 NFSv4.1을 통해 공유되는 영구 볼륨을 사용하여 파일에 액세스합니다. 이를 위해서는 AUTH_SYS 인증 방법이 필요합니다.



== 라이센싱

Astra Data Store 미리 보기를 사용하려면 Astra Data Store 미리 보기 라이센스가 있어야 모든 기능을 사용할 수 있습니다. https://www.netapp.com/cloud-services/astra/data-store-form/["여기에서 등록하십시오"^] Astra Data Store Preview 라이센스를 얻으려면 라이센스 다운로드 지침은 가입 후 발송됩니다.



== AutoSupport 구성

Astra 데이터 저장소 미리 보기를 사용하려면 AutoSupport를 활성화하고 AutoSupport 백엔드에 연결해야 합니다. 이는 직접 인터넷 액세스 또는 프록시 구성을 통해 가능합니다.

를 클릭합니다 link:../get-started/install-ads.html#install-the-astra-data-store-cluster["필수 원격 측정 AutoSupport 번들을 보내는 데 사용되는 주기적 설정입니다"] 변경해서는 안 됩니다. 주기적인 AutoSupport 번들 전송을 해제하면 클러스터가 잠기며, 주기적인 설정을 다시 활성화할 때까지 새 볼륨을 생성할 수 없습니다.



== 다음 단계

를 봅니다 link:quick-start.html["빠른 시작"] 개요.



== 를 참조하십시오

link:capabilities.html["Astra Data Store 미리보기 제한"]
