---
sidebar: sidebar 
permalink: get-started/requirements.html 
keywords: kubernetes cluster, cluster requirements, version requirements, supported versions, apps, supported apps, mariadb, mysql, postgres, kubernetes version, ubuntu, image type, networking 
summary: 먼저 환경에 대한 지원을 확인하십시오. 
---
= Astra 데이터 저장소 요구 사항
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


먼저 귀사의 환경이 Astra Data Store 요구 사항을 충족하는지 확인하십시오.

Astra Data Store는 베어 메탈 및 VM 기반 구축을 모두 지원합니다. Astra Data Store 클러스터는 4개 이상의 작업자 노드가 있는 Kubernetes 클러스터에서 실행될 수 있습니다. Astra Data Store 소프트웨어는 동일한 Kubernetes 클러스터에서 실행 중인 다른 애플리케이션과 함께 사용할 수 있습니다.

* <<Kubernetes worker node resources>>
* <<Hardware and software>>
* <<Networking>>
* <<Astra Trident>>
* <<Container Network Interfaces>>
* <<Licensing>>



NOTE: Astra Control Center에서 Astra Data Store 클러스터를 관리하려는 경우, Astra Data Store 클러스터가 를 충족하는지 확인하십시오 https://docs.netapp.com/us-en/astra-control-center/get-started/requirements.html#kubernetes-cluster-general-requirements["Astra Control Center에서 관리할 클러스터에 대한 요구 사항입니다"^] 여기에 설명된 요구 사항 외에



== Kubernetes 작업자 노드 리소스

Kubernetes 클러스터의 각 작업자 노드에 있는 Astra Data Store 소프트웨어에 할당하기 위해 필요한 리소스 요구사항은 다음과 같습니다.

|===
| 리소스 | 최소 | 최대 


| Astra Data Store 클러스터에 있는 노드 수입니다 | 4 | 16 


| 데이터 드라이브 수입니다  a| 
* 3(별도의 캐시 디바이스가 있는 경우)
* 4(캐시 디바이스가 없는 경우)

| 14 


| 데이터 드라이브 크기입니다 | 100GiB | 4TiB 


| 선택적 캐시 디바이스의 수입니다 | 1(8GiB 크기) | 해당 없음 
|===
Astra Data Store는 각 Kubernetes 작업자 노드에 대해 다음과 같은 vCPU 및 RAM 조합을 지원합니다.

* RAM 38GiB의 vCPU 9개
* RAM 94GiB의 vCPU 23개



NOTE: 최상의 쓰기 성능을 얻으려면 지연 시간이 짧은 전용 고성능 캐시 디바이스를 구성해야 합니다.

각 작업자 노드에는 다음과 같은 추가 요구 사항이 있습니다.

* Astra Data Store 로그 파일을 저장할 호스트 디스크(부팅)의 여유 공간 100GiB 이상
* 클러스터, 데이터 및 관리 트래픽을 위한 최소 1개의 10GbE 또는 더 빠른 네트워크 인터페이스 필요에 따라 추가 1GbE 또는 더 빠른 인터페이스를 사용하여 관리 트래픽을 분리할 수 있습니다.




== 하드웨어 및 소프트웨어

Astra Data Store 소프트웨어는 다음과 같은 하드웨어 플랫폼, 소프트웨어 및 스토리지 구성에서 검증되었습니다. 를 방문하십시오 link:../support/get-help-ads.html["NetApp 커뮤니티 지원"] Kubernetes 클러스터 구성이 다른 경우



=== 하드웨어 플랫폼

* Dell R640
* Dell R740
* HPE DL360
* HPE DL380
* Lenovo SR630
* Lenovo SR650



NOTE: VM 기반 배포에서는 에 호환되는 것으로 나열된 서버를 사용할 수도 있습니다 https://www.vmware.com/resources/compatibility/search.php["VMware 호환성 가이드 를 참조하십시오"^].



=== 스토리지

Astra Data Store는 SATA, SAS 및 NVMe TLC SSD로 검증되었습니다.

VM 기반 배포의 경우 가상 디스크 또는 패스스루 드라이브로 제공된 드라이브를 사용할 수 있습니다.

[NOTE]
====
* 호스트에서 하드웨어 RAID 컨트롤러 뒤에 SSD를 사용하는 경우 "통과" 모드를 사용하도록 하드웨어 RAID 컨트롤러를 구성합니다.
* 각 드라이브에는 고유한 일련 번호가 있어야 합니다. VM 생성 시 가상 머신 고급 설정에 disk.enableuid=true 속성을 추가합니다.


====


=== 소프트웨어

* 하이퍼바이저: Astra Data Store는 vSphere 7.0을 통해 VMware 기반 VM 구축을 통해 검증되었습니다. KVM 기반 배포는 Astra Data Store에서 지원되지 않습니다.
* Astra Data Store는 다음과 같은 호스트 운영 체제에서 검증되었습니다.
+
** Red Hat Enterprise Linux 8.4
** Red Hat Enterprise Linux 8.2
** Red Hat Enterprise Linux 7.9
** Red Hat Enterprise Linux CoreOS(RHCOS)
** CentOS 8
** Ubuntu 20.04


* Astra Data Store는 다음과 같은 Kubernetes 배포에서 검증되었습니다.
+
** Red Hat OpenShift 4.6 - 4.9
** Google Anthos 1.8 - 1.10
** Kubernetes 1.20 ~ 1.23
** Rancher RKE 1.3.3





NOTE: Astra Data Store에는 스토리지 프로비저닝 및 오케스트레이션을 위한 Astra Trident가 필요합니다. Astra Trident 버전 21.10.1 ~ 22.04가 지원됩니다. 를 참조하십시오 link:setup-ads.html#install-astra-trident["Astra Trident 설치 지침"].



== 네트워킹

Astra Data Store에는 MVIP를 위해 클러스터당 하나의 IP 주소가 필요합니다. MIP와 동일한 서브넷에서 사용되지 않거나 구성되지 않은 IP 주소여야 합니다. Astra Data Store 관리 인터페이스는 Kubernetes 노드의 관리 인터페이스와 동일해야 합니다.

또한 다음 표에 설명된 대로 각 노드를 구성할 수 있습니다.


NOTE: 이 표에는 MIP: 관리 IP 주소 CIP: 클러스터 IP 주소 MVIP: 관리 가상 IP 주소가 사용됩니다

|===
| 구성 | IP 주소가 필요합니다 


| 노드당 1개의 네트워크 인터페이스  a| 
* 노드당 2개:
+
** MIP/CIP: 노드당 관리 인터페이스에서 사전 구성된 IP 주소 1개
** 데이터 IP: MIP와 동일한 서브넷의 노드당 사용되지 않거나 구성되지 않은 IP 주소 1개






| 노드당 2개의 네트워크 인터페이스  a| 
* 노드당 3개:
+
** MIP: 노드당 관리 인터페이스에 사전 구성된 IP 주소 1개
** CIP: MIP와 다른 서브넷의 노드별 데이터 인터페이스에 사전 구성된 IP 주소 1개
** 데이터 IP: CIP와 동일한 서브넷에 있는 노드당 사용되지 않거나 구성되지 않은 IP 주소 1개




|===

NOTE: 이러한 구성에는 VLAN 태그가 사용되지 않습니다.



== 아스트라 트리덴트

Astra Data Store를 사용하려면 스토리지 프로비저닝 및 오케스트레이션을 위해 애플리케이션 Kubernetes 클러스터를 Astra Trident를 실행 중이어야 합니다. Astra Trident 버전 21.10.1 ~ 22.04가 지원됩니다. Astra Data Store는 로 구성할 수 있습니다 link:../get-started/setup-ads.html#set-up-astra-data-store-as-storage-backend["스토리지 백엔드"] Astra Trident를 사용하여 영구 볼륨 프로비저닝



== 컨테이너 네트워크 인터페이스

Astra Data Store는 다음 컨테이너 네트워크 인터페이스(CNIs)를 사용하여 검증되었습니다.

* RKE 클러스터용 Calico
* 바닐라 Kubernetes 클러스터용 Calico 및 Weave Net CNIs
* Red Hat OpenShift Container Platform(OCP)용 OpenShift SDN
* Google Anthos의 Cilium


[NOTE]
====
* Cilium CNI와 함께 배포된 Astra Data Store에는 HostPort 지원을 위한 포트맵 플러그인이 필요합니다. 'cilium-config configMap'에 'cni-chaining-mode:portmap'을 추가하고 Cilium Pod를 다시 시작하여 CNI chaining 모드를 활성화할 수 있습니다.
* 방화벽 지원 구성은 Calico 및 OpenShift SDN CNIs에서만 지원됩니다.


====


== 라이센싱

Astra Data Store에는 전체 기능을 사용하려면 유효한 라이센스가 필요합니다.

https://www.netapp.com/cloud-services/astra/data-store-form/["여기에서 등록하십시오"^] Astra Data Store 라이센스를 취득합니다. 라이센스 다운로드 지침은 가입 후 발송됩니다.



== 다음 단계

를 봅니다 link:quick-start.html["빠른 시작"] 개요.



== 를 참조하십시오

link:capabilities.html["Astra 데이터 저장소 제한"]
